version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chatwoot_production
      POSTGRES_USER: chatwoot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

  chatwoot:
    image: chatwoot/chatwoot:4.11
    restart: always
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    expose:
      - "3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      FRONTEND_URL: ${FRONTEND_URL}
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: db
      POSTGRES_USERNAME: chatwoot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: chatwoot_production
      RAILS_LOG_TO_STDOUT: "true"
      SERVE_STATIC_FILES: "true"

  worker:
    image: chatwoot/chatwoot:4.11.0
    restart: always
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      FRONTEND_URL: ${FRONTEND_URL}
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: db
      POSTGRES_USERNAME: chatwoot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: chatwoot_production

volumes:
  postgres_data:
  redis_data:
